CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

# OLED display via zmk-dongle-display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=4096

CONFIG_ZMK_SLEEP=n
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_HID=y
CONFIG_ZMK_USB=y

# Disable CDC ACM (so HID is the sole USB interface on interface 0)
CONFIG_ZMK_USB_LOGGING=n
CONFIG_USB_CDC_ACM=n

# USB 1.1 boot protocol compatibility
CONFIG_ZMK_USB_BOOT=y
