include:
  - board: xiao_ble/nrf52840/zmk
    shield: totem_left
  - board: xiao_ble/nrf52840/zmk
    shield: totem_right
  - board: nice_nano//zmk
    shield: totem_dongle
  - board: nice_nano//zmk
    shield: settings_reset
  - board: xiao_ble/nrf52840/zmk
    shield: settings_reset
